# Generated by Django 4.2.5 on 2023-10-11 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0002_remove_order_products_orderitem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
