# Generated by Django 4.2.5 on 2023-10-11 21:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0004_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
