# Generated by Django 4.2.5 on 2023-10-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0007_product_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="added_date",
            field=models.DateTimeField(),
        ),
    ]
