# Generated by Django 4.2.5 on 2023-10-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0010_order_products_alter_orderitem_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="count",
            new_name="quantity",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="count",
            new_name="quantity",
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
